import "@/styles/globals.css";

import type { Metadata } from "next";
import { FontWrapper } from "@/components/font-wrapper";
import { MaxWidthWrapper } from "@/components/max-with-wrapper";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";

export const metadata: Metadata = {
  title: "Attendance Percentage Calculator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <FontWrapper>
          <MaxWidthWrapper>
            <SiteHeader />
            {children}
            <SiteFooter />
          </MaxWidthWrapper>
        </FontWrapper>
      </body>
    </html>
  );
}
