import "@/styles/globals.css";

import type { Metadata } from "next";
import { MaxWidthWrapper } from "@/components/max-with-wrapper";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";
import { Background } from "@/components/background";
import { FontWrapper } from "@/components/font-wrapper";
import { QueryProvider } from "@/components/query-provider";

export const metadata: Metadata = {
  title: "Attendance Percentage Calculator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="dark">
        <QueryProvider>
          <FontWrapper>
            <MaxWidthWrapper>
              <Background />
              <SiteHeader />
              {children}
              <SiteFooter />
            </MaxWidthWrapper>
          </FontWrapper>
        </QueryProvider>
      </body>
    </html>
  );
}
