import "@/styles/globals.css";

import type { Metadata } from "next";
import { MaxWidthWrapper } from "@/components/max-with-wrapper";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";
import { Background } from "@/components/background";
import { FontWrapper } from "@/components/font-wrapper";
import { QueryProvider } from "@/components/query-provider";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Attendance Percentage Calculator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="dark">
        <QueryProvider>
          <FontWrapper>
            <MaxWidthWrapper>
              <Background />
              <SiteHeader />
              <div className="min-h-[calc(100dvh-6rem)] lg:min-h-screen lg:max-h-screen place-items-center place-content-center px-4">
                {children}
              </div>
              <SiteFooter />
              <Toaster position="top-center" />
            </MaxWidthWrapper>
          </FontWrapper>
        </QueryProvider>
      </body>
    </html>
  );
}
